### ISSUE TITLE
Include tags in code

### ISSUE THREAD

**Issue by DanielSchimit** [FronkonGames/Steam-Games-Scraper#1]
FronkonGames,

Is it possible to insert tags in this csv? I'm having a huge difficulty because to finish my data analysis I need the tags column, or each tag described with 1 or 0 to determine if this tag belongs to the game line or not.

Tags are very important for data analysis and I realized that the data is up to date and it's not long before I finish.

**Comment by FronkonGames** [comment]
Hi Daniel,

you mean add a column of tags? Can you give an example?

The code that generates the CVS file from the JSON is ConvertToCSV.py, you can modify it to add the columns you want. If you think these changes might be of interest to others, please make a Pull Request.

Regards.

**Comment by DanielSchimit** [comment]
yes, example of what I want to get:
           Tags
GTA V: 'Open World', 'Action', 'Multiplayer', 'Automobile Sim', 'Crime', 'Third Person', 'First-Person', 'Shooter', 'Mature'
'Adventure', 'Singleplayer', 'Third-Person Shooter', 'Racing', 'Co-op', 'Atmospheric', 'Sandbox', 'Funny', 'Great Soundtrack', 'Comedy', 'Moddable'.

I don't know how to pull the tags, I've never worked with a steam api, another thing I'm a data science student and I know a little bit of python 1 year of experience. I know it was the def parsegame that would need to be called. In script SteamGamesScraper.py

I think so:

 game['tags'] = []
  if 'tags' in app:
    for tag in app['tags']:
      game['tags'].append(tag['description'])

I'm learning a lot with kaggle, when I put my notebook talking about steam I'll mention that you were my data source.

in script converttoCSV.py 

here add 'tags'

with open('games.csv', 'w', encoding="utf-8") as fin:
    header = [
      'AppID',
      'Name',
      'Release date',
      'Required age',
      'Price',
      'DLC count',
      'About the game',
      'Supported languages',
      'Full audio languages',
      'Reviews',
      'Header image',
      'Website',
      'Support url',
      'Support email',
      'Windows',
      'Mac',
      'Linux',
      'Metacritic score',
      'Metacritic url',
      'Achievements',
      'Recommendations',
      'Notes',
      'Developers',
      'Publishers',
      'Categories',
      'Genres',
      'Screenshots',
      'Movies'
    ]

Also sorry for any bad translation, I use translator I don't know English.
Sorry, I don't know if I did the right code...

**Comment by DanielSchimit** [comment]
Martin, good morning!

I tried everything this morning, I did several tests with the steam api I couldn't insert the tags in the json.

I beg for your help! please.

**Comment by FronkonGames** [comment]
Hi Daniel, if by "tags" you mean the tags that appear on the Steam page of a game:

![Untitled-1](https://user-images.githubusercontent.com/100220849/180650317-c0679ff6-4ffa-4055-a957-4f7d57db815e.jpg)

I'm afraid that information is not provided by the Steam API, sorry.

Could you use the "categories" field?

**Comment by DanielSchimit** [comment]
Categories field is not for subcategory analysis.

so I'll tell you what I want to do, I want to do a mass analysis of how much each game sold with taxes and without taxes, then we'll put the option to filter for example 'mystery' tag.
The idea is to find which tags fit best to sell more.
With the tags I'll know the theme and try to sort them to find out which set is more efficient according to the sale.
Then I'll try to make a chart of the most sold and least sold tags according to the main tag.
there's a guy who used steam spy tags to complement the spreadsheet data.
[](https://github.com/nik-davis/steam-data-science-project/tree/master/notebooks)

if you use his idea to complement json, you will have a full dataset generator that can generate insights to help many game developers to get a sense of whether the game is worth investing in subdivided into tags.

What do you think would you like to contribute?

**Comment by FronkonGames** [comment]
I think this is a fantastic idea. I just looked at the SteamSpy API, and it provides very interesting information. I will add the option to add SteamSpy.

Thanks for the idea Daniel 👍

**Comment by DanielSchimit** [comment]
I will provide you with a table that goes from 0.99 to 69.99 dollars with 240 thousand reviews, the worksheet is tabable, that is, just select and pull because billing is standardized by the value with taxes. you can turn this worksheet into a math equation.
[](https://github.com/DanielSchimit/portfolio/blob/main/STEAM/Indie%20data%20steam/planilha_com_todos_os_valores.xlsx)
I can help you with data science, do you accept?

**Comment by FronkonGames** [comment]
SteamSpy is now supported, and I've added some interesting fields (among them the 'tags').

For now this repository will be just a tool to extract data, I prefer to use [Kaggle](https://www.kaggle.com/datasets/fronkongames/steam-games-dataset) to analyze it.

**Comment by DanielSchimit** [comment]
thank you
