### ISSUE TITLE
python .\SteamGamesScraper.py doesn't generate anything

### ISSUE THREAD

**Issue by ElementMedia** [FronkonGames/Steam-Games-Scraper#2]
I was wondering if this tool is still working? I installed the dependencies and started with "python .\SteamGamesScraper.py" however nothing is generated. I get the following returned pretty quick:

[i 15:44:12] Steam Games Scraper 1.2.0 by Martin Bustos <fronkongames@gmail.com>.
[i 15:44:12] Loading 'discarted.json'.
[i 15:44:12] New dataset created.
[i 15:44:12] 74200 apps discarted.
[E 15:44:12] File update.csv not found.
[i 15:44:12] Done.

**Comment by FronkonGames** [comment]
Fixed in the version 1.2.1, thanks for reporting the error!
